### PR TITLE
Update all the way to RTM and update person lists

### PR DESCRIPTION
**Pull request by analogrelay**
Supercedes #79 
Supercedes #81 
Supercedes #82 
- Delete `node_modules` (it doesn't need to be checked in)
- Migrate to RC2
- Migrate to RTM
- Convert to `netcoreapp1.0`
- Add @cjqian and @ZestyBread to the person set lists

### CODE REVIEW

**Comment by cjqian** [comment]
😁😁😁

**Comment by Eilon** [comment]
It's still not live on the site, though - I'm having trouble publishing 😦

**Comment by cjqian** [comment]
No worries, baby steps! 👶

**Comment by Eilon** [comment]
It's now live! Thanks!

**Pull request merged**
